### PR TITLE
[ADD] stiloconcepto: add product-attribute OCA module

### PR DESCRIPTION
**Pull request by AlejandroVI99**
Adding the module Supplier info prices in sales pricelists of OCA, inside de project will be able to create sales price lists based on supplier price lists.

### CODE REVIEW

**Comment by NicolasOT** [comment]
+1 FUNCTIONAL TEST - EVERYTHING OK PROCEED PULL

I'm not authorized to merge

image


cc
@hugho-ad 
@AlejandroVI99 
@luisg123v

**Comment by hugho-ad** [comment]
@AlejandroVI99 

please update this

**Comment by hugho-ad** [comment]
@NicolasOT 

podemos hacer merge? no afectamos operaciones?

**Comment by NicolasOT** [comment]
@hugho-ad 
Proceder con el merge, cliente notificado y dio su +1

**Pull request merged**
